/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.flyguide.Fly', null, global);
goog.exportSymbol('proto.flyguide.FlyId', null, global);
goog.exportSymbol('proto.flyguide.GetAllFly', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flyguide.FlyId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.flyguide.FlyId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.flyguide.FlyId.displayName = 'proto.flyguide.FlyId';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flyguide.FlyId.prototype.toObject = function(opt_includeInstance) {
  return proto.flyguide.FlyId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flyguide.FlyId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flyguide.FlyId.toObject = function(includeInstance, msg) {
  var f, obj = {
    nameorigin: jspb.Message.getFieldWithDefault(msg, 1, ""),
    namedestiny: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flyguide.FlyId}
 */
proto.flyguide.FlyId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flyguide.FlyId;
  return proto.flyguide.FlyId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flyguide.FlyId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flyguide.FlyId}
 */
proto.flyguide.FlyId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNameorigin(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamedestiny(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flyguide.FlyId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flyguide.FlyId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flyguide.FlyId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flyguide.FlyId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNameorigin();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNamedestiny();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string nameOrigin = 1;
 * @return {string}
 */
proto.flyguide.FlyId.prototype.getNameorigin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.flyguide.FlyId.prototype.setNameorigin = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string nameDestiny = 2;
 * @return {string}
 */
proto.flyguide.FlyId.prototype.getNamedestiny = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.flyguide.FlyId.prototype.setNamedestiny = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flyguide.GetAllFly = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.flyguide.GetAllFly.repeatedFields_, null);
};
goog.inherits(proto.flyguide.GetAllFly, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.flyguide.GetAllFly.displayName = 'proto.flyguide.GetAllFly';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.flyguide.GetAllFly.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flyguide.GetAllFly.prototype.toObject = function(opt_includeInstance) {
  return proto.flyguide.GetAllFly.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flyguide.GetAllFly} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flyguide.GetAllFly.toObject = function(includeInstance, msg) {
  var f, obj = {
    fliesList: jspb.Message.toObjectList(msg.getFliesList(),
    proto.flyguide.Fly.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flyguide.GetAllFly}
 */
proto.flyguide.GetAllFly.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flyguide.GetAllFly;
  return proto.flyguide.GetAllFly.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flyguide.GetAllFly} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flyguide.GetAllFly}
 */
proto.flyguide.GetAllFly.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.flyguide.Fly;
      reader.readMessage(value,proto.flyguide.Fly.deserializeBinaryFromReader);
      msg.addFlies(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flyguide.GetAllFly.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flyguide.GetAllFly.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flyguide.GetAllFly} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flyguide.GetAllFly.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFliesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.flyguide.Fly.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Fly flies = 1;
 * @return {!Array.<!proto.flyguide.Fly>}
 */
proto.flyguide.GetAllFly.prototype.getFliesList = function() {
  return /** @type{!Array.<!proto.flyguide.Fly>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.flyguide.Fly, 1));
};


/** @param {!Array.<!proto.flyguide.Fly>} value */
proto.flyguide.GetAllFly.prototype.setFliesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.flyguide.Fly=} opt_value
 * @param {number=} opt_index
 * @return {!proto.flyguide.Fly}
 */
proto.flyguide.GetAllFly.prototype.addFlies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.flyguide.Fly, opt_index);
};


proto.flyguide.GetAllFly.prototype.clearFliesList = function() {
  this.setFliesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.flyguide.Fly = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.flyguide.Fly, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.flyguide.Fly.displayName = 'proto.flyguide.Fly';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.flyguide.Fly.prototype.toObject = function(opt_includeInstance) {
  return proto.flyguide.Fly.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.flyguide.Fly} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flyguide.Fly.toObject = function(includeInstance, msg) {
  var f, obj = {
    flyid: (f = msg.getFlyid()) && proto.flyguide.FlyId.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    flynumber: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.flyguide.Fly}
 */
proto.flyguide.Fly.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.flyguide.Fly;
  return proto.flyguide.Fly.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.flyguide.Fly} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.flyguide.Fly}
 */
proto.flyguide.Fly.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.flyguide.FlyId;
      reader.readMessage(value,proto.flyguide.FlyId.deserializeBinaryFromReader);
      msg.setFlyid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFlynumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.flyguide.Fly.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.flyguide.Fly.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.flyguide.Fly} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.flyguide.Fly.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlyid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.flyguide.FlyId.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFlynumber();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional FlyId flyId = 1;
 * @return {?proto.flyguide.FlyId}
 */
proto.flyguide.Fly.prototype.getFlyid = function() {
  return /** @type{?proto.flyguide.FlyId} */ (
    jspb.Message.getWrapperField(this, proto.flyguide.FlyId, 1));
};


/** @param {?proto.flyguide.FlyId|undefined} value */
proto.flyguide.Fly.prototype.setFlyid = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.flyguide.Fly.prototype.clearFlyid = function() {
  this.setFlyid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.flyguide.Fly.prototype.hasFlyid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.flyguide.Fly.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.flyguide.Fly.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.flyguide.Fly.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.flyguide.Fly.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 flyNumber = 4;
 * @return {number}
 */
proto.flyguide.Fly.prototype.getFlynumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.flyguide.Fly.prototype.setFlynumber = function(value) {
  jspb.Message.setField(this, 4, value);
};


goog.object.extend(exports, proto.flyguide);
